name: Build and push a container of the API server and the custom mongo image

on: [push]

env:
  REGISTRY: ghcr.io


permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build-and-deploy-api-server:
    name: Build and push API Server container to Docker Hub
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: "${{ github.repository }}/api_server"

    steps:
    - uses: actions/checkout@v5

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push API server image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./server/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  build-and-deploy-custom-mongo:
    name: Build and push Custom Mongo image to Docker Hub
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: "${{ github.repository }}/custom_mongo"

    steps:
    - uses: actions/checkout@v5

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Mongo image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./azure/init-db/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        secrets: |
          id=MONGO_USER,env=MONGO_USER
          id=MONGO_PASSWORD,env=MONGO_PASSWORD
