# File: .github/workflows/workflow.yml
name: Deploy API server to Azure App Service

on: [push]

env:
  AZURE_WEBAPP_NAME: netflix-api-server
  AZURE_WEBAPP_PACKAGE_PATH: 'server'
  NODE_VERSION: '21.4'

jobs:
  build-and-deploy:
    name: Build and Deploy API Server to Azure Web Apps
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm install, build, and test
      run: |
        npm install
      working-directory: server

    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v3
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}